### ISSUE TITLE
Modules load problem in workers

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/Metarhia#34]
Some modules, for example `argon2` can't be loaded in worker threads.

Try `load.js` with the following code:
```js
'use strict';

const { Worker } = require('worker_threads');

const argon2 = require('argon2');
console.dir({ argon2 });

new Worker('./thread.js');
```
and `thread.js` with the following code:
```js
'use strict';

const argon2 = require('argon2');

console.dir({ argon2 });
```
we will get exception:
```
Error: Module did not self-register.
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:775:18)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
    at Module.require (internal/modules/cjs/loader.js:663:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at bindings (.../node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (.../node_modules/argon2/argon2.js:4:37)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
```
We need to find solution to use worker thread in impress. @nechaido you can assign this task to developers.

**Comment by tshemsedinov** [comment]
Refs: https://github.com/nodejs/node/pull/23319
Refs: https://github.com/nodejs/node/issues/21481

**Comment by lundibundi** [comment]
Starting from Node.js 11.11.0 (https://github.com/nodejs/node/pull/26175) it should be possible to use native addons from multiple worker threads as logs as they are
- an N-API addon, or
- declared as context-aware using NODE_MODULE_INIT() as described above

(https://nodejs.org/api/addons.html#addons_worker_support)

Where the latter basically means that the addon properly manages its global/static state to protect it against race conditions, clean up its data when instance shutdowns,  doesn't store persistent JS object references and doesn't access JS objects from the wrong context (not the one they were created in). Therefore using `NODE_MODULE_INIT` instead of `NODE_MODULE` tells Node.js that the module respects the given rules.
